### ISSUE TITLE
Error thrown when user tries to add existing game

### ISSUE THREAD

**Issue by jessekeasley** [PCMRating/pcmrating#68] opened 2015-07-27 00:26 UTC
I tried adding a game with the right steam code (730) and it won't let me
![pcmr rating issue](https://cloud.githubusercontent.com/assets/12804673/8896780/eb5fe4ac-3449-11e5-8687-0a5a3299ff9f.JPG)

**Comment by tjhorner** [comment] 2015-07-27 20:22
@Lockyy you might want to change the default error page and link them to the new issue page

I'll see if I can reproduce locally.

**Comment by Lockyy** [comment] 2015-07-27 20:25
Sounds like a good idea. I'll get that into the new version of the site later on tonight.

I looked into this this morning when I got a message on Reddit about it. Must have missed this message. Turns out that when the Steam store went down, the API we're using to grab information also went down. Need to add error handling to the API call.

It's all back up now and working.

**Comment by jessekeasley** [comment] 2015-07-27 21:49
Hey so I just checked again and well.....it still doesnt work
After looking on reddit (where I posted it again), it says that they fixed it.....still doesnt work

**Comment by Lockyy** [comment] 2015-07-27 21:57
Found the issue. http://www.pcmrating.com/games/counter-strike-global-offensive Global Offensive has already been added.

Error will be fixed soon.

**Closed** 2015-07-27 22:01 UTC
